type JENNIE = "Jen";
type Upper = Uppercase<JENNIE>;
// type Upper = "JEN"
type Lower = Lowercase<JENNIE>;
// type Lower = "jen"
type Capital = Capitalize<JENNIE>;
// type Capital = "Jen"
type UnCaptial = Uncapitalize<JENNIE>;
// type UnCaptial = "jen"
